### ISSUE TITLE
Use envsubst instead of sed for deploy.sh variables

### ISSUE THREAD

**Issue by pingiun** [GipHouse/Website#315]
### One-sentence description

`envsubst` is a tool in gettext (so it should be installed already) that can replace bash style variables in a piece of text, for example:

```bash
$ cat template.txt
This is a ${TEMPLATE}
$ export TEMPLATE=test
$ envsubst < template.txt
This is a test
```

### Motivation

Sed has some tricky things you have to deal with, while we just want to replace some variables, `envsubst` works well for this.

**Comment by joren485** [comment]
This has been done in #322
