### ISSUE TITLE
Optional comment fields in questionnaires are actually required

### ISSUE THREAD

**Issue by JobDoesburg** [GipHouse/Website#467]
### One-sentence description
Optional comment fields in questionnaires are actually required

### How to reproduce the bug
1. Fill in a questionnaire
2. Keep optional fields empty
3. Submit

### Expected behaviour
Accept empty optional fields

**Comment by joren485** [comment]
This is not as much a bug as a feature that was never implemented. That being sad, this is a nice feature to have.
