### ISSUE TITLE
Comments of saved questionaire aren't shown

### ISSUE THREAD

**Issue by 9Y0** [GipHouse/Website#595]
### One-sentence description
I saved my questionaire and when I later went back to it, my comments were replaced by a number. Note that this didn't happen for questions where only text had to be filled in.
![afbeelding](https://user-images.githubusercontent.com/15932140/166443156-febb0426-76ab-43b4-8dc6-0b90eccfa1c5.png)

### How to reproduce the bug

1. Go to a questionnaire.
2. Fill in some agree-disagree question and give a comment.
3. Save the questionnaire.
4. Close the page, and reopen the questionnaire.
5. The numbers are there...

### Expected behaviour
I would expect that my comments would appear.

**Comment by JobDoesburg** [comment]
Thanks for notifying us! We have resolved the issue. Luckily, it was not the case that your comments were not stored. It was only that they were not properly being displayed on reloading the page. In a few minutes, the patched version of the website will come online

**Comment by 9Y0** [comment]
Unfortunately, I probably hit Save again which meant that my answers were deleted :facepalm:. Luckily I did not fill in that much yet... Thanks for fixing it so quickly though!
