### ISSUE TITLE
Convert plaintext URLs in project descriptions to hyperlinks

### ISSUE THREAD

**Issue by 1058274** [GiPHouse/Website#616]
### One-sentence description

Obvious plaintext URLs in project descriptions should automatically be detected and converted to HTML hyperlinks.

### Desired functionality

Currently, project descriptions can not be set in any way to present URLs as HTML hyperlinks due to HTML character encoding. Superusers should be able to set a plaintext project description containing URLs where the URLs get converted to HTML hyperlinks in the front-end. This way, page visitors can directly visit a page mentioned in the project description using a single click.

### Motivation
Nitpicking, perfectionism, and user experience.

### Suggested implementation

- Use [Django's built-in filter urlize](https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#urlize) to convert obvious URLs to HTML hyperlinks [here](https://github.com/GiPHouse/Website/blob/main/website/projects/templates/projects/index.html#L18).
  - _Obvious_ URLs because `example.nl` does not get converted but `www.example.nl` and `https://example.nl` do.
- A superuser of the current production website should remove the HTML code from the [current project descriptions](https://giphouse.nl/projects/2023/spring/) for the projects `Chemrade Plant dashboard` and `PUC Mathematics scavenger hunt`. This step is not directly related to this repository, as it is likely a configuration mistake.
- Optionally but probably redundant, use [Django's striptags](https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#striptags) to remove any HTML as a preprocessing step. When used in combination with `urlize`, the current production website would have displayed proper hyperlinks. However, I think this step is not necessary if the user setting the project descriptions is aware that HTML can not directly be embedded in project descriptions.

**Comment by 1058274** [comment]
> I would suggest implementing an HTML field with TinyMCE as done in https://github.com/svthalia/concrexit

I had a look at TinyMCE's `HTMLField` and it looks like a better solution indeed, as it allows the admins to customize the project description in different ways and to preview the project descriptions in realtime instead of having to rely on some conversion from `urlize` that only gets applied after saving. 

Other than hyperlinks, what other styling features should be allowed in the editor? Also, the output should go through a `bleach` tag that has been configured based on the predetermined allowed styling features, similar to how it has been implemented @ Thalia, correct?

**Comment by JobDoesburg** [comment]
> Other than hyperlinks, what other styling features should be allowed in the editor? Also, the output should go through a `bleach` tag that has been configured based on the predetermined allowed styling features, similar to how it has been implemented @ Thalia, correct?

Maybe strong or italic text would be nice too, as well as `ul`s and `ol`s. I think the set Thalia implemented is very well thought-through so I propose to just copy it from them :)
